version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gosec

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable:
        - shadow

    misspell:
      locale: US

issues:
  exclude-rules:
    - text: "misspelling of"
      linters:
        - misspell
